update gh action for adv season stats

diff --git a/.github/workflows/update_adv_passing.yml b/.github/workflows/update_adv_passing.yml
--- a/.github/workflows/update_adv_passing.yml
+++ b/.github/workflows/update_adv_passing.yml
@@ -1,30 +1,49 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
-  #schedule:
-    # runs every day at 7:00 AM UTC in Jan, Feb, Sep-Dec
-   # - cron:  '0 7,14 * 1,2,9-12 *'
   workflow_dispatch:
+  schedule:
+    # runs every thursday at 7:00 AM UTC in Jan, Feb, Sep-Dec
+    # PFR updates these data on  the Wednesday following the week's games
+    - cron:  '0 7 * 1,2,9-12 4'
 
-name: Update Advanced Passing Stats
+name: update_adv_season_stats
 
 jobs:
-  update:
-    name: Update Data
-    runs-on: macOS-latest
+  pfr_adv_season_stats:
+    runs-on: ${{ matrix.config.os }}
+
+    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
+
+    strategy:
+      fail-fast: false
+      matrix:
+        config:
+          - {os: ubuntu-latest,   r: 'release'}
+
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+      R_KEEP_PKG_SOURCE: yes
+
     steps:
       - uses: actions/checkout@v2
+
       - uses: r-lib/actions/setup-r@v1
+        with:
+          r-version: ${{ matrix.config.r }}
+          http-user-agent: ${{ matrix.config.http-user-agent }}
+          use-public-rspm: true
 
-      - name: Install packages
-        run: |
-          install.packages(c("tidyverse", "janitor","nflreadr"))
-        shell: Rscript {0}
+      - uses: r-lib/actions/setup-r-dependencies@v1
 
-      - name: Update advanced passing stats
-        run: Rscript -e 'source("auto/passing.R")'
+      - name: Run update script
+        run: Rscript -e 'source("auto/update_adv_season_stats.R")'
 
       - name: Commit updated data
         run: |
+          git config --local user.email "actions@github.com"
+          git config --local user.name "GitHub Actions"
           git pull
           git add data
-          git commit -m "Automated advanced passing stats updates `date`" || echo "No changes to commit"
+          git commit -m "Automated advanced season stats scrape `date`" || echo "No changes to commit"
           git push || echo "No changes to commit"
